#ifndef APPLICATION_H
#define APPLICATION_H
#include "event/BlockingQueue.h"
#include "event/GameEvent.h"
#include "game/GameController.h"
#include "input/InputHandler.h"
#include "network/NetworkHandler.h"
#include "network/NetworkSender.h"

/**
 * @brief The main entry point of the client application.
 *
 * This class initializes and manages the lifecycle of all core components:
 * networking, game logic, input handling, and event queues.
 */
class Application {
private:
    /** @brief Queue for events received from the server to be processed by the client. */
    std::unique_ptr<BlockingQueue<GameEvent> > fromServerToClient;

    /** @brief Queue for events generated by the client to be sent to the server. */
    std::unique_ptr<BlockingQueue<GameEvent> > fromClientToServer;

    /** @brief Handles user input from the keyboard. */
    std::unique_ptr<InputHandler> inputHandler;

    /** @brief Manages the WebSocket connection and incoming messages. */
    std::unique_ptr<NetworkHandler> networkHandler;

    /** @brief Controls the game state and logic. */
    std::unique_ptr<GameController> gameController;

    /** @brief Consumes events from the output queue and sends them over the network. */
    std::unique_ptr<NetworkSender> networkSender;

public:
    /**
     * @brief Constructs the Application and initializes all components.
     * @param url The WebSocket URL of the game server.
     */
    explicit Application(const std::string &url);

    /**
     * @brief Starts the application loop.
     *
     * This method starts the network threads and enters the main game loop,
     * processing input and updating the game state until the application is closed.
     */
    void execute() const;
};


#endif //APPLICATION_H
